classdef ui < handle
    properties
        app
    end
    methods
        function ui = ui_builder(~)
            ui = struct();
            % Create figure and panel on it
            ui.f = figure('Name', 'Simple Image Viewer', 'NumberTitle', 'Off','WindowState','maximized', 'WindowScrollWheelFcn', @scrollWheelMoved);
            % Create panels on the figure
            ui.buttonPanel = uipanel(ui.f, 'Units', 'normalized', 'Position', [0 0 0.2 1]); % [left bottom width height]
            ui.axesPanel = uipanel(ui.f, 'Units', 'normalized', 'Position', [0.2 0 0.8 1]);
            folder_ico = imread('./folder.png');
            folder_ico = imresize(folder_ico, [20, 20]);
            next_ico = imread('./next.png');
            next_ico = imresize(next_ico, [20, 20]);
            prev_ico = imread('./prev.png');
            prev_ico = imresize(prev_ico, [20, 20]);
            % Create axes on the axes panel
            ui.ax1 = axes(ui.axesPanel, 'Position', [0.01 0.2 0.49 0.7]);
            ui.ax2 = axes(ui.axesPanel, 'Position', [0.5 0.2 0.49 0.7]);
            % Create button on the panel
            ui.stack_dropdown = uicontrol(ui.buttonPanel, 'Style', 'popupmenu', 'String', stack_paths, ...
                'Units', 'normalized', 'Position', [0.2 0.9 0.6 0.06], 'Callback', @load_images_callback);
            % add open directory button beside the dropdown
            ui.open_dir_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', '', ...
                'Units', 'normalized','Position', [0.8 0.93 0.08 0.03], 'CData', folder_ico,...
                'Callback', @open_directory_callback, 'Enable', 'on');
            ui.drawMasks_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', 'Draw mask', ...
                'Units', 'normalized','Position', [0.2 0.7 0.4 0.06], 'Callback', @draw_masks_callback, 'Enable', 'on');
            ui.drawAllMasks_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', 'Do all', ...
                'Units', 'normalized','Position', [0.6 0.7 0.2 0.06], 'Callback', @draw_all_masks_callback, 'Enable', 'on');
            % deadZone_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', 'Mark dead zone', ...
            %     'Units', 'normalized','Position', [0.2 0.64 0.6 0.06], 'Callback', @mark_dead_zone_callback, 'Enable', 'on');
            % add a checkbox for forced state
            ui.forced_checkbox = uicontrol(ui.buttonPanel, 'Style', 'checkbox', 'String', 'Forced', ...
                'Units', 'normalized', 'Position', [0.8 0.7 0.2 0.06], 'Callback', @forced_callback, 'Enable', 'on');
            ui.Gr_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', 'Get Gr', ...
                'Units', 'normalized','Position', [0.2 0.64 0.4 0.06], 'Callback', @get_Gr, 'Enable', 'on');
            ui.Gr_AllStack_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', 'Get all', ...
                'Units', 'normalized','Position', [0.6 0.64 0.2 0.06], 'Callback', @Gr_all_stacks_callback, 'Enable', 'on');
            ui.shortenStack_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', 'Shorten stack', ...
                'Units', 'normalized','Position', [0.2 0.58 0.4 0.06], 'Callback', @shorten_stack_callback, 'Enable', 'on');
            ui.shortenAllStack_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', 'Do all', ...
                'Units', 'normalized','Position', [0.6 0.58 0.2 0.06], 'Callback', @shorten_all_stack_callback, 'Enable', 'on');
            ui.alignStack_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', 'Align stack', ...
                'Units', 'normalized','Position', [0.2 0.52 0.4 0.06], 'Callback', @align_stack_callback, 'Enable', 'on');
            ui.alignAllStack_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', 'Align all', ...
                'Units', 'normalized','Position', [0.6 0.52 0.2 0.06], 'Callback', @align_all_stacks_callback, 'Enable', 'on');
            ui.alignStack_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', 'Align stack', ...
                'Units', 'normalized','Position', [0.2 0.52 0.4 0.06], 'Callback', @align_stack_callback, 'Enable', 'on');
            ui.alignAllStack_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', 'Align all', ...
                'Units', 'normalized','Position', [0.6 0.52 0.2 0.06], 'Callback', @align_all_stacks_callback, 'Enable', 'on');
            ui.timestampStack_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', 'Timestamp stack', ...
            'Units', 'normalized','Position', [0.2 0.46 0.4 0.06], 'Callback', @timestamp_stack, 'Enable', 'on');
            ui.timestampAllStack_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', 'Do all', ...
                'Units', 'normalized','Position', [0.6 0.46 0.2 0.06], 'Callback', @timestamp_all_stacks, 'Enable', 'on');
    
            ui.logs_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', 'Logs', ...
                'Units', 'normalized','Position', [0.51 0.32 0.3 0.06], 'Callback', @show_logs_callback, 'Enable', 'on');
            ui.save_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', 'Save', ...
                'Units', 'normalized','Position', [0.2 0.32 0.3 0.06], 'Callback', @save_stack_callback, 'Enable', 'on');
            uicontrol(ui.buttonPanel, 'Style', 'text', 'String', 'From Frame:', ...
                'Units', 'normalized', 'Position', [0.1 0.22 0.4 0.08]);    %[left bottom width height]
            uicontrol(ui.buttonPanel, 'Style', 'text', 'String', 'To Frame:', ...
                'Units', 'normalized', 'Position', [0.5 0.22 0.4 0.08]);
            ui.from_frame = uicontrol(ui.buttonPanel, 'Style', 'edit', ...
                'Units', 'normalized', 'Position', [0.2 0.22 0.2 0.04], 'String', '1');
            ui.to_frame = uicontrol(ui.buttonPanel, 'Style', 'edit', ...
                'Units', 'normalized', 'Position', [0.6 0.22 0.2 0.04], 'String', '1');
            ui.slider = uicontrol(ui.axesPanel, 'Style', 'slider', 'Units', 'normalized', 'Position', [0.1 0.06 0.6 0.08], ...
                'Callback', @slider_callback, 'Visible', 'on');
            ui.frame_number = uicontrol(ui.axesPanel, 'Style', 'text','Units', 'normalized', 'Position', [0.7 0.04 0.1 0.08], 'String', '1','FontSize', 14);
            % Create a "Next stack" button
            ui.nextStack_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', '', ...
                'Units', 'normalized', 'Position', [0.1 0.93 0.08 0.03], 'CData', next_ico,...
                'Callback', @next_stack_callback, 'Enable', 'on');
            ui.prevStack_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', '', ...
                'Units', 'normalized', 'Position', [0.03 0.93 0.08 0.03], 'CData', prev_ico,...
                    'Callback', @prev_stack_callback, 'Enable', 'on');
            ui.skip_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', 'Skip', ...
                'Units', 'normalized','Position', [0.2 0.15 0.6 0.06], 'Callback', @skip_alignment_callback, 'Enable', 'off');
            ui.stack_label = uicontrol(ui.buttonPanel, 'Style', 'text', 'String', 'Stack #1', ...
                'Units', 'normalized', 'Position', [0.2 0.96 0.6 0.03]);
            % create info UI
            uicontrol(ui.buttonPanel, 'Style', 'text', 'String', 'N:', ...
                'Units', 'normalized', 'Position', [-0.1 0.82 0.4 0.08]);
            uicontrol(ui.buttonPanel, 'Style', 'text', 'String', 'f:', ...
                'Units', 'normalized', 'Position', [0.15 0.82 0.4 0.08]);
            uicontrol(ui.buttonPanel, 'Style', 'text', 'String', 'Iter:', ...
                'Units', 'normalized', 'Position', [0.4 0.82 0.4 0.08]);
            ui.N_info = uicontrol(ui.buttonPanel, 'Style', 'edit', ...
                'Units', 'normalized', 'Position', [0.15 0.87 0.1 0.04], 'String', '4');
            ui.f_info = uicontrol(ui.buttonPanel, 'Style', 'edit', ...
                'Units', 'normalized', 'Position', [0.4 0.87 0.1 0.04], 'String', '4');
            ui.i_info = uicontrol(ui.buttonPanel, 'Style', 'edit', ...
                'Units', 'normalized', 'Position', [0.65 0.87 0.1 0.04], 'String', '1');
            ui.goto_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', 'load', ...
            'Units', 'normalized','Position', [0.77 0.87 0.15 0.04], 'Callback', @goto_callback);
            ui.function_dropdown = uicontrol(ui.buttonPanel, 'Style', 'popupmenu', ...
                'String', function_list, ...
                'Units', 'normalized', 'Position', [0.2 0.04 0.6 0.06]);
            ui.execute_button = uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', '', ...
                'Units', 'normalized', 'Position', [0.8 0.07 0.08 0.03], 'CData', next_ico,...
                'Callback', @execute_selected_function);
                % uicontrol(ui.buttonPanel, 'Style', 'pushbutton', 'String', '', ...
                %     'Units', 'normalized', 'Position', [0.1 0.93 0.08 0.03], 'CData', next_ico,...
                %      'Callback', @next_stack_callback, 'Enable', 'on');
            % Create play/pause button beside the scrollbar
            play_icon = imread('./play.png');
            ui.play_icon = imresize(play_icon, [40, 40]);
            pause_icon = imread('./pause.png');
            ui.pause_icon = imresize(pause_icon, [40, 40]);
            ui.play_pause_button = uicontrol(ui.axesPanel, 'Style', 'pushbutton', 'Units', 'normalized', ...
                'Position', [0.01 0.06 0.08 0.08], 'CData', ui.play_icon, 'Callback', @play_pause_callback);
            ui.speed_dropdown = uicontrol(ui.axesPanel, 'Style', 'popupmenu', 'String', speeds, ...
                'Units', 'normalized', 'Position', [0.01 0.001 0.08 0.08], 'Callback', @set_speed_callback);
            ui.play_timer = timer('ExecutionMode', 'fixedRate', 'Period', 0.1, 'TimerFcn', @play_timer_callback);
            % Create indicators for aligned and shortened statuses
            ui.aligned_indicator = create_indicator(ui.buttonPanel, [0 0.8 0.3 0.05], "Aligned", @remove_alignment_callback);
            ui.shortened_indicator = create_indicator(ui.buttonPanel, [0.5 0.8 0.3 0.05], "Shortened", @remove_shortening_callback);
        end
        function indicator = create_indicator(~, parent, position, label, delete_callback)
            indicator = uicontrol(parent, 'Style', 'text', 'String', label, ...
            'Units', 'normalized', 'Position', [position(1)+0.1 position(2) position(3) position(4)], 'BackgroundColor', 'red');
            % if delete_callback is provided, set the callback for the indicator
            if exist('delete_callback', 'var')
                % add a dustbin icon to delete the indicator
                dustbin = imread('./bin_icon.png');
                dustbin = imresize(dustbin, [20, 20]);
                uicontrol(parent, 'Style', 'pushbutton', 'Units', 'normalized', ...
                    'Position', [position(1) + position(3) + 0.05 position(2) 0.08 0.05], 'CData', dustbin, ...
                    'Callback', delete_callback);
            end
        end
        function toggle_indicator(~,indicator, status)
            if status
                set(indicator, 'BackgroundColor', 'green');
            else
                set(indicator, 'BackgroundColor', 'red');
            end
        end
    end
end